name: Challenge 1
on:
  pull_request:
    branches:
    - main

jobs:
  my_job:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: build
      run: npm ci
    - name: test
      run: npm test
    #- name: Analizar con Sonar
    #  uses: sonarsource/sonarqube-scan-action@master
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
    
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Jira Create issue
      uses: atlassian/gajira-create@v3
      with:
        # Key of the project
        project: ${{ vars.JIRA_PROJECT }}
        # Type of the issue to be created. Example: 'Incident'
        issuetype: "Task"
        # Issue summary
        summary: "PR Created"
        # Issue description
        description: "A PR was created"
    
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"

    - uses: Jerome1337/comment-pull-request@v1.0.4
      with:
        comment-message: "Issue ${{ steps.create.outputs.issue }}"
        # Delete previous comment
        #delete-previous-comment: # optional
            
          
    
    

