name: Challenge 1
on:
  workflow_dispatch:

jobs:
  my_job:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: build
      run: npm ci
    - name: test
      run: npm test
