name: CHALLENGE
on:
  workflow_dispatch:
jobs:
  scan-and-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Analizar con Sonar
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
      
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  

      - name: "Example show SonarQube Quality Gate Status value"
        if: failure()
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"


  approve-PR:
    needs: scan-and-quality-gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1

  close-PR:
    if: ${{ scan-and-quality-gate.steps.sonarqube-quality-gate-check.outputs.quality-gate-status == FAILED }}
    runs-on: ubuntu-latest
    steps:
      - run: echo SUCCES
    
    
      

      
      
      

  
