name: CHALLENGE
on:
  workflow_dispatch:
jobs:
  scan-and-quality-gate:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sonarqube-quality-gate-check.outputs.test }}
    steps:
      - uses: actions/checkout@v4

      - name: Analizar con Sonarr
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
      
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  

      - name: "Example show SonarQube Quality Gate Status value"
        if: failure()
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

      - name: Close Pull
        if: failure()
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: 1
          comment: Auto-closing pull request
          delete-branch: false


  approve-PR:
    needs: scan-and-quality-gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 2

      - name: Login JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: IDG
          issuetype: "Check Aproved PR"
          summary: Pendiente de aprobar PullRequest ${{ github.repository }}
          description: Compare branch
          fields: '{"customfield_10171": "test"}'

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
    
    

      
      
      

  
